### ISSUE TITLE
This plug-in is great, but it seems that it cannot read and write win11 clipboard images, but it can monitor hasImage

### ISSUE THREAD

**Issue by Tester-957** [CrossCopy/tauri-plugin-clipboard#21]
Latest examples used

![image](https://github.com/CrossCopy/tauri-plugin-clipboard/assets/58334417/f0ca8878-9aa0-49c9-bd7d-20d87551037f)

**Comment by HuakunShen** [comment]
I just checked on Win11. The problem indeed exists. It comes from an upstream library. [clipboard-rs](https://github.com/ChurchTao/clipboard-rs)

@ChurchTao Can you take a quick look? I also get `The image format could not be determined` on Win11 when I run the example code in [clipboard-rs](https://github.com/ChurchTao/clipboard-rs) repo.

**Comment by ChurchTao** [comment]
@Tester-957 
My bad, it will be fixed soon.
https://github.com/ChurchTao/clipboard-rs/pull/15

**Comment by HuakunShen** [comment]
@Tester-957 Fixed in v0.6.2.
@ChurchTao Thank you!

**Comment by Tester-957** [comment]
> @Tester-957在 v0.6.2 中修复。 @ChurchTao谢谢你！
我发现
The new version fixes the problem of reading the clipboard, but writing pictures to the clipboard still fails. In the example, click the Write Image (Base64) or Write Image (Binary) buttons to read them in the example interface. This image cannot be pasted in third-party applications such as WeChat or the drawing software that comes with win11.
![image](https://github.com/CrossCopy/tauri-plugin-clipboard/assets/58334417/a1e0b104-1a0d-4ef1-9b41-e6ebc5745c5d)

**Comment by Tester-957** [comment]
Thank you very much for your help 🌹. Today I also tried to use the examples in MAC OS and found a small problem: when I used the "Feishu" office software and used its screen cutting function, the cut screen image could not be monitored by the examples (hasImage:false ) Others are also “false”. I'll test other software tomorrow to see if this problem exists (can provide more information if needed).

**Comment by HuakunShen** [comment]
@Tester-957 Confirmed the Feishu screenshot problem on Mac, Win11 and Ubuntu22. Same problem on Mac, but not on Win11 or Ubuntu22. 
Also tested WeChat on MacOS. WeChat's screenshots could be read by [clipboard-rs](https://github.com/ChurchTao/clipboard-rs). 

Note: screenshot written by Feishu could be read by https://crates.io/crates/arboard.
We may need to look at the difference between Arboard and clipboard-rs.

Also confirmed the Windows image pasting problem.

**Comment by HuakunShen** [comment]
Feishu clipboard image bug located. 

Here is the available format for a regular screenshot: `["public.png", "Apple PNG pasteboard type", "public.tiff", "NeXT TIFF v4.0 pasteboard type"]`

Here is the available format for a Feishu screenshot `["public.tiff", "NeXT TIFF v4.0 pasteboard type"]`

`clipboard.dataForType(NSPasteboardTypeTIFF)` will return the screenshot made by Feishu.
You may want to add a type checking for `has()` and `get_image()`. @ChurchTao

**Comment by ChurchTao** [comment]
@Tester-957 @HuakunShen 
My bad again, new version released.
https://github.com/ChurchTao/clipboard-rs/releases/tag/v0.1.6

**Comment by HuakunShen** [comment]
Mac's TIFF support and Windows image paste bug fixed in v0.6.3
https://github.com/CrossCopy/tauri-plugin-clipboard/releases/tag/v0.6.3

- https://github.com/ChurchTao/clipboard-rs/releases/tag/v0.1.6
- https://github.com/ChurchTao/clipboard-rs/issues/17
- https://github.com/ChurchTao/clipboard-rs/issues/19

**Comment by Tester-957** [comment]
@HuakunShen During use, I found a possible performance problem🤔. When using the API to read the Image or using the listener, I found that when the image is large, the main process will be blocked. This is the blocking time-consuming situation I debugged. It can happen in rust layer.
![image](https://github.com/CrossCopy/tauri-plugin-clipboard/assets/58334417/e12990bf-906b-499b-96ce-42dc894ba467)

**Comment by HuakunShen** [comment]
@Tester-957 Thank you for mentioning. Addressed in https://github.com/CrossCopy/tauri-plugin-clipboard/issues/25

**Comment by Tester-957** [comment]
> @Tester-957 Thank you for mentioning. Addressed in #25谢谢你的提及。已解决 #25 In release mode it should be much faster. 在发布模式下它应该快得多。
> 
> You can open a new issue for a new bug. Otherwise I might miss your message in this closed issue.您可以为新错误打开一个新问题。否则我可能会错过你在这个已关闭问题中的留言。

🆗，Thank you!
